#############################################################################
# Makefile for building: LearnQt
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  LearnQt.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile LearnQt.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-HelloWorld \
		sub-HelloWindow \
		sub-ProgressBar \
		sub-Serial \
		sub-Stream \
		sub-FileStream \
		sub-CanWrite \
		sub-Math \
		sub-MultiThread \
		sub-QtThread \
		sub-SocketCANWrite \
		sub-SocketCAN


sub-HelloWorld-qmake_all:  FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile
	cd HelloWorld/ && $(MAKE) -f Makefile qmake_all
sub-HelloWorld: FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile
sub-HelloWorld-make_first: FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-HelloWorld-all: FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-HelloWorld-clean: FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-HelloWorld-distclean: FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HelloWorld-install_subtargets: FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-HelloWorld-uninstall_subtargets: FORCE
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HelloWindow-qmake_all:  FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile
	cd HelloWindow/ && $(MAKE) -f Makefile qmake_all
sub-HelloWindow: FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile
sub-HelloWindow-make_first: FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-HelloWindow-all: FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-HelloWindow-clean: FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-HelloWindow-distclean: FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HelloWindow-install_subtargets: FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-HelloWindow-uninstall_subtargets: FORCE
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ProgressBar-qmake_all:  FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile
	cd ProgressBar/ && $(MAKE) -f Makefile qmake_all
sub-ProgressBar: FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile
sub-ProgressBar-make_first: FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-ProgressBar-all: FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-ProgressBar-clean: FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-ProgressBar-distclean: FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ProgressBar-install_subtargets: FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-ProgressBar-uninstall_subtargets: FORCE
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Serial-qmake_all:  FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile
	cd Serial/ && $(MAKE) -f Makefile qmake_all
sub-Serial: FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile
sub-Serial-make_first: FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-Serial-all: FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-Serial-clean: FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-Serial-distclean: FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Serial-install_subtargets: FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-Serial-uninstall_subtargets: FORCE
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Stream-qmake_all:  FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile
	cd Stream/ && $(MAKE) -f Makefile qmake_all
sub-Stream: FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile
sub-Stream-make_first: FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-Stream-all: FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-Stream-clean: FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-Stream-distclean: FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Stream-install_subtargets: FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-Stream-uninstall_subtargets: FORCE
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-FileStream-qmake_all:  FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile
	cd FileStream/ && $(MAKE) -f Makefile qmake_all
sub-FileStream: FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile
sub-FileStream-make_first: FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-FileStream-all: FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-FileStream-clean: FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-FileStream-distclean: FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-FileStream-install_subtargets: FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-FileStream-uninstall_subtargets: FORCE
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-CanWrite-qmake_all:  FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile
	cd CanWrite/ && $(MAKE) -f Makefile qmake_all
sub-CanWrite: FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile
sub-CanWrite-make_first: FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-CanWrite-all: FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-CanWrite-clean: FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-CanWrite-distclean: FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-CanWrite-install_subtargets: FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-CanWrite-uninstall_subtargets: FORCE
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Math-qmake_all:  FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile
	cd Math/ && $(MAKE) -f Makefile qmake_all
sub-Math: FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile
sub-Math-make_first: FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-Math-all: FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-Math-clean: FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-Math-distclean: FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Math-install_subtargets: FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-Math-uninstall_subtargets: FORCE
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-MultiThread-qmake_all:  FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile
	cd MultiThread/ && $(MAKE) -f Makefile qmake_all
sub-MultiThread: FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile
sub-MultiThread-make_first: FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-MultiThread-all: FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-MultiThread-clean: FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-MultiThread-distclean: FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-MultiThread-install_subtargets: FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-MultiThread-uninstall_subtargets: FORCE
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-QtThread-qmake_all:  FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile
	cd QtThread/ && $(MAKE) -f Makefile qmake_all
sub-QtThread: FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile
sub-QtThread-make_first: FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-QtThread-all: FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-QtThread-clean: FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-QtThread-distclean: FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-QtThread-install_subtargets: FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-QtThread-uninstall_subtargets: FORCE
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-SocketCANWrite-qmake_all:  FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile
	cd SocketCANWrite/ && $(MAKE) -f Makefile qmake_all
sub-SocketCANWrite: FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile
sub-SocketCANWrite-make_first: FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-SocketCANWrite-all: FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-SocketCANWrite-clean: FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-SocketCANWrite-distclean: FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-SocketCANWrite-install_subtargets: FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-SocketCANWrite-uninstall_subtargets: FORCE
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-SocketCAN-qmake_all:  FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile
	cd SocketCAN/ && $(MAKE) -f Makefile qmake_all
sub-SocketCAN: FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile
sub-SocketCAN-make_first: FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-SocketCAN-all: FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-SocketCAN-clean: FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-SocketCAN-distclean: FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-SocketCAN-install_subtargets: FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-SocketCAN-uninstall_subtargets: FORCE
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: LearnQt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		LearnQt.pro
	$(QMAKE) -o Makefile LearnQt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
LearnQt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile LearnQt.pro

qmake_all: sub-HelloWorld-qmake_all sub-HelloWindow-qmake_all sub-ProgressBar-qmake_all sub-Serial-qmake_all sub-Stream-qmake_all sub-FileStream-qmake_all sub-CanWrite-qmake_all sub-Math-qmake_all sub-MultiThread-qmake_all sub-QtThread-qmake_all sub-SocketCANWrite-qmake_all sub-SocketCAN-qmake_all FORCE

make_first: sub-HelloWorld-make_first sub-HelloWindow-make_first sub-ProgressBar-make_first sub-Serial-make_first sub-Stream-make_first sub-FileStream-make_first sub-CanWrite-make_first sub-Math-make_first sub-MultiThread-make_first sub-QtThread-make_first sub-SocketCANWrite-make_first sub-SocketCAN-make_first FORCE
all: sub-HelloWorld-all sub-HelloWindow-all sub-ProgressBar-all sub-Serial-all sub-Stream-all sub-FileStream-all sub-CanWrite-all sub-Math-all sub-MultiThread-all sub-QtThread-all sub-SocketCANWrite-all sub-SocketCAN-all FORCE
clean: sub-HelloWorld-clean sub-HelloWindow-clean sub-ProgressBar-clean sub-Serial-clean sub-Stream-clean sub-FileStream-clean sub-CanWrite-clean sub-Math-clean sub-MultiThread-clean sub-QtThread-clean sub-SocketCANWrite-clean sub-SocketCAN-clean FORCE
distclean: sub-HelloWorld-distclean sub-HelloWindow-distclean sub-ProgressBar-distclean sub-Serial-distclean sub-Stream-distclean sub-FileStream-distclean sub-CanWrite-distclean sub-Math-distclean sub-MultiThread-distclean sub-QtThread-distclean sub-SocketCANWrite-distclean sub-SocketCAN-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-HelloWorld-install_subtargets sub-HelloWindow-install_subtargets sub-ProgressBar-install_subtargets sub-Serial-install_subtargets sub-Stream-install_subtargets sub-FileStream-install_subtargets sub-CanWrite-install_subtargets sub-Math-install_subtargets sub-MultiThread-install_subtargets sub-QtThread-install_subtargets sub-SocketCANWrite-install_subtargets sub-SocketCAN-install_subtargets FORCE
uninstall_subtargets: sub-HelloWorld-uninstall_subtargets sub-HelloWindow-uninstall_subtargets sub-ProgressBar-uninstall_subtargets sub-Serial-uninstall_subtargets sub-Stream-uninstall_subtargets sub-FileStream-uninstall_subtargets sub-CanWrite-uninstall_subtargets sub-Math-uninstall_subtargets sub-MultiThread-uninstall_subtargets sub-QtThread-uninstall_subtargets sub-SocketCANWrite-uninstall_subtargets sub-SocketCAN-uninstall_subtargets FORCE

sub-HelloWorld-check:
	@test -d HelloWorld/ || mkdir -p HelloWorld/
	cd HelloWorld/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWorld/HelloWorld.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-HelloWindow-check:
	@test -d HelloWindow/ || mkdir -p HelloWindow/
	cd HelloWindow/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/HelloWindow/HelloWindow.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-ProgressBar-check:
	@test -d ProgressBar/ || mkdir -p ProgressBar/
	cd ProgressBar/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/ProgressBar/ProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-Serial-check:
	@test -d Serial/ || mkdir -p Serial/
	cd Serial/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Serial/Serial.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-Stream-check:
	@test -d Stream/ || mkdir -p Stream/
	cd Stream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Stream/Stream.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-FileStream-check:
	@test -d FileStream/ || mkdir -p FileStream/
	cd FileStream/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/FileStream/FileStream.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-CanWrite-check:
	@test -d CanWrite/ || mkdir -p CanWrite/
	cd CanWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/CanWrite/CanWrite.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-Math-check:
	@test -d Math/ || mkdir -p Math/
	cd Math/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/Math/Math.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-MultiThread-check:
	@test -d MultiThread/ || mkdir -p MultiThread/
	cd MultiThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/MultiThread/MultiThread.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-QtThread-check:
	@test -d QtThread/ || mkdir -p QtThread/
	cd QtThread/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/QtThread/QtThread.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-SocketCANWrite-check:
	@test -d SocketCANWrite/ || mkdir -p SocketCANWrite/
	cd SocketCANWrite/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCANWrite/SocketCANWrite.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-SocketCAN-check:
	@test -d SocketCAN/ || mkdir -p SocketCAN/
	cd SocketCAN/ && ( test -e Makefile || $(QMAKE) /home/fmi/Development/LearnQt/SocketCAN/SocketCAN.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-HelloWorld-check sub-HelloWindow-check sub-ProgressBar-check sub-Serial-check sub-Stream-check sub-FileStream-check sub-CanWrite-check sub-Math-check sub-MultiThread-check sub-QtThread-check sub-SocketCANWrite-check sub-SocketCAN-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

